version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
