# be sure to set Actions > Workflow permissions to "Read and write permissions"
name: "Build and release"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: "Build PHAR and add to release"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://www.php.net/supported-versions.php
        php-version:
          - "8.3"
        os:
          - "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          ini-values: "phar.readonly=Off"
        env:
          fail-fast: true
      - name: "Build PHAR"
        run: "php build-phar.php"
      - name: Calculate checksum
        run: |
          cd bin
          sha256sum expose-php-fpm-settings.phar > expose-php-fpm-settings.phar.sha256.txt
          sha256sum expose-php-fpm-settings.sh > expose-php-fpm-settings.sh.sha256.txt
      - name: "Release"
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            bin/expose-php-fpm-settings.phar
            bin/expose-php-fpm-settings.phar.sha256.txt
            bin/expose-php-fpm-settings.sh
            bin/expose-php-fpm-settings.sh.sha256.txt
